### ISSUE TITLE
`pdr.Data` cannot find explicit pointers nested inside PVL groups

### ISSUE THREAD

**Issue by m-stclair** [MillionConcepts/pdr#15]
for instance,
`Data` finds this pointer:

```
^IMAGE = ("2259ML0120880010804894C00_DRCL.IMG")
```
but not this pointer:
```
GROUP                              = GEOMETRIC_CAMERA_MODEL_PARMS
 ^MODEL_DESC                         = "GEOMETRIC_CM.TXT"
```

or this pointer:
```
OBJECT                  = L0_FILE                                             
  ^L0_LINE_PREFIX_TABLE = "M3G20081124T020103_V01_L0.IMG"  
```

resolution might require recursively iterating over `PVLModule.values()` or an entirely different approach.

**Comment by m-stclair** [comment]
partial resolution in c2c4b4407e08f0653113def25e9cc49f3df5cff7, requires more testing

**Comment by m-stclair** [comment]
ugh: a219523

**Comment by michaelaye** [comment]
i wanted to share this nicely written post about general purpose recursive structure digging. I found it very clear, clean, and simple (which doesn't happen often for recursive code for me) : http://nvie.com/posts/modifying-deeply-nested-structures/

**Comment by michaelaye** [comment]
oh, and i do this simple thing for index tables, where the pointers are also at different places sometimes, not sure it's applicable/useful here:

https://github.com/michaelaye/nbplanetary/blob/master/planetarypy/pds/indexes.py#L114-L118

**Comment by m-stclair** [comment]
the 'general purpose recursive structure digging' technique is very close to how i solved this problem previously, and is good for tracking cases in which there are PVL 'file area' blocks one level up from the PVL block that contains an actual object description. the question is whether we want to have `Data`'s pointers be sequences -- and I suppose we probably do. currently as a stopgap I am using, basically, a truncated version of that:

```
def dig_for(mapping, target, predicate=eq):
    nests = [v for v in mapping.values() if isinstance(v, Mapping)]
    level_keys = [(k, v) for k, v in mapping.items() if predicate(k, target)]
    if nests:
        level_keys += reduce(
            add, [dig_for(nest, target, predicate) for nest in nests]
        )
    return level_keys


def dig_for_value(mapping, target, predicate=eq):
    dug = dig_for(mapping, target, predicate)
    if dug:
        return dug[0][1]
    return None
```

...and then as methods of `Data`:
```
    def labelget(self, text):
        return dig_for_value(self.LABEL, text)

    def labelblock(self, text):
        what_got_dug = dig_for_value(self.LABEL, text)
        if not isinstance(what_got_dug, Mapping):
            return self.LABEL
        return what_got_dug
```

**Comment by m-stclair** [comment]
...and to grab all pointers:
```
def get_pds3_pointers(label=None, local_path=None):
    if label is None:
        label = pvl.load(local_path)
    return dig_for(label, "^", lambda k, v: k.startswith(v))
```

**Comment by m-stclair** [comment]
closing this for now with these stopgap solutions. see #21 for continued work.
