### ISSUE TITLE
`pvl` can't currently load most MER navcam labels

### ISSUE THREAD

**Issue by m-stclair** [MillionConcepts/pdr#19]
on, for instance, https://pds-imaging.jpl.nasa.gov/data/mer/opportunity/mer1om_0xxx/data/navcam/site0003/1nn013eff03cyl00p1652l000m2.img ,
`pvl` hangs without output.

examining the process reveals that it appears to be stuck in an infinite loop parsing the IMAGE object block.

**Comment by rbeyer** [comment]
Oh my, that's bad.  Will investigate.

**Comment by rbeyer** [comment]
This should now be fixed with *pvl* version 1.3.0.

**Comment by m-stclair** [comment]
> This should now be fixed with _pvl_ version 1.3.0.

verifying that _pvl_ 1.3.0 is loading these labels smoothly. thank you!
