### ISSUE TITLE
refactor read_table

### ISSUE THREAD

**Issue by m-stclair** [MillionConcepts/pdr#27]
several options are possible. one leading candidate is:

1. attempt to infer whether the table is text or binary. This could be a condition like: are there ASCII data types in the format definition OR does the first line of the table decode correctly as ASCII/Unicode?
2. If the table is text, refer to a mapping of text data type names to python types. Then load it with numpy.loadtxt or or whatever based on those types and column names, punting to other parsers if that fails.
3. if the table is binary, look up sample types as struct-style definitions

**Comment by michaelaye** [comment]
* It's only ever *data* tables that are binary, correct? Index tables are always ASCII and data tables could be both ASCII and binary, right?
* Are there examples where the label information is insufficient to read the data table?

**Comment by m-stclair** [comment]
Yes, I am only referring to data tables here.

There is one very common set of cases in which the label is insufficient to read a data table: when labels refer to external format specification files that are not locally available. 

There are also cases in which binary tables have underspecified / ambiguous data types due to ambiguities in the PDS3 standards (endianness is not always clear, for instance). 

I have also found some instances in older data sets in which specifications are nonstandard or missing, although I can’t cite them off the top of my head.

**Comment by m-stclair** [comment]
changes made to support several MSL and MRO datasets have solved many of the major issues referenced in this issue. I am closing it for now in favor of opening more specific issues.
