### ISSUE TITLE
Minimum version of Python required is higher than indicated

### ISSUE THREAD

**Issue by wkiri** [MillionConcepts/pdr#29]
The README for `pdr` specifies that the minimum Python version required is 3.8, but the package depends on `dustgoggles` which seems to require a higher version.  I got this error when attempting to install `pdr`: 

> ERROR: Package 'dustgoggles' requires a different Python: 3.8.9 not in '>=3.9'

**Comment by m-stclair** [comment]
That line in the README is out of date. We will correct this when merging our development branch in the next day or two. Thank you for drawing our attention to this!
