### ISSUE TITLE
PDS4 XML label is opened as if a PDS3 label

### ISSUE THREAD

**Issue by msbentley** [MillionConcepts/pdr#3]
When testing `pdr.read()` on a PDS4 product, I get:
```
In [22]: pdr.read('cam_raw_sc_cam2_image_20201015t035549_43_f__t0004.xml')
 *** Cannot find label data. *** 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/pdr/lib/python3.9/site-packages/pvl/lexer.py in lexer(s, g, d)
    428                     yield None
--> 429                     t = yield t
    430                 lexeme = ""

ValueError: Expecting an Aggregation Block, an Assignment Statement, or an End Statement, but found "<?xml version="1.0" encoding="utf-8"?>"
```
it looks like the label is being parsed by PVL and not handed off to pds4_tools?

**Comment by cmillion** [comment]
Thanks for helping to test! I think that analysis is correct. I'll fix it.

**Comment by cmillion** [comment]
This should work now. An issue is that PVL and XML return different object types as "LABEL". I would like LABEL to always be the same object type. I might try to convert the XML into a `pvl` object, but I'm not sure if that's logically coherent.

**Comment by msbentley** [comment]
OK, thanks - I'll give it a try! Do you use the file extension to distinguish? At some (still fairly distant) point the extension of PDS4 labels will become something different from .xml, but that bridge can be crossed when we come to it ;-)

**Comment by cmillion** [comment]
Yes. What will the extension be in the distant future?

**Comment by msbentley** [comment]
I think the front-runner is `.lblx`.

With the latest version of pdr, my above example (BepiColombo MCAM image) works fine!
