### ISSUE TITLE
Support reading from URL

### ISSUE THREAD

**Issue by msbentley** [MillionConcepts/pdr#31]
I'm not sure if this is expected behaviour, but passing a URL to a data product (PDS3/4 detached label or PDS3 product with attached label) gives a `FileNotFoundError` error trying to open the "parent" directory. (note that the pds4 tools reader supports this natively, but not when pdr is used on a PDS4 label).

**Comment by m-stclair** [comment]
It's expected behavior, although we should probably return a more useful error message. pdr doesn't currently support read-over-HTTP. We have some exploratory plans for this, but haven't fully defined how we'd like the interface and architecture to work.
