### ISSUE TITLE
cassini missing from supported_missions docs

### ISSUE THREAD

**Issue by michaelaye** [MillionConcepts/pdr#37]
Just noticed that no comment was made for cassini data yet.
Won't be straight forward, I'm afraid, lots of different data sets.

**Comment by cmillion** [comment]
Yeah. It's on our priority list but haven't gotten to it yet. I'm confident that we can handle the volume of data sets. Are there any particular gotchas that you think we should look out for?

**Comment by cmillion** [comment]
As a note, we only list a data set as "supported" when we have established test coverage for it. I think it's very likely that much of the Cassini data will already open correctly with `pdr`. We just don't have test coverage yet.

**Comment by thareUSGS** [comment]
Cassini RADAR has been migrated to PDS4 (and more recently released). A good chance to test the still existing PDS3 labels and PDS4 labels to see if the same results are had. https://pdsimage2.wr.usgs.gov/Missions/Cassini/

**Comment by m-stclair** [comment]
just a brief note that we've implemented support for almost all cassini products in the development branch, and this will be included in the next release of `pdr`.

**Comment by Sierra-MC** [comment]
The Cassini product support is now specified by data type in the [supported datasets document](https://github.com/MillionConcepts/pdr/blob/main/supported_datasets.md).
