### ISSUE TITLE
Failure to parse Rosetta/MIDAS PDS3 image

### ISSUE THREAD

**Issue by msbentley** [MillionConcepts/pdr#4]
Testing PDR on this atomic force microscopy image/array:

https://pdssbn.astro.umd.edu/holdings/ro-c-midas-3-ext3-samples-v3.0/data/img/img_1627006_1627309_027_zs.lbl
https://pdssbn.astro.umd.edu/holdings/ro-c-midas-3-ext3-samples-v3.0/data/img/img_1627006_1627309_027_zs.img

I get:

```
----> 1 test = pdr.read('IMG_1627006_1627309_027_ZS.LBL')

~/Dropbox/software/pds/pdr/pdr/__init__.py in read(fp)
     11 
     12 def read(fp):
---> 13     return Data(fp)
     14 
     15 def open(fp):

~/Dropbox/software/pds/pdr/pdr/pdr.py in __init__(self, filename)
    597         setattr(self, "pointers", [k for k in self.LABEL.keys() if k[0] == "^"])
    598         try:
--> 599             _ = [
    600                 setattr(
    601                     self,

~/Dropbox/software/pds/pdr/pdr/pdr.py in <listcomp>(.0)
    601                     self,
    602                     pointer[1:] if pointer.startswith("^") else pointer,
--> 603                     pointer_to_function[pointer](filename, self.LABEL),
    604                 )
    605                 for pointer in self.pointers

KeyError: '^ARCHIVE_CONTEXT_DESC'
```
where this pointer is actually to a document, not a data object in the file.

**Comment by cmillion** [comment]
Good catch. Yeah... there are a lot of examples like this. I haven't figured out how to handle them in a general case yet.

You'll also find that there are table definitions stored in external reference files (via pointer). Same problem.

**Comment by msbentley** [comment]
OK, thanks. Let me know if you prefer that I raise issues for problems I find, or if you prefer to call out specific product types etc. for testing!

**Comment by cmillion** [comment]
Both approaches are good with me! It really depends on how quickly you lose patience with things breaking.

**Comment by cmillion** [comment]
This is a strange format beyond even just the the pointers to external files. I'll have to think about this for a little bit.

**Comment by cmillion** [comment]
You should be able to get the image out now, and it won't crash. The pointers to the external files will just return empty strings while I figure out a general solution to that.

**Comment by cmillion** [comment]
Is this what you expect it to look like?
![image](https://user-images.githubusercontent.com/1483210/104832523-9f23e800-585f-11eb-8c68-bb56fd9cb6e6.png)

**Comment by cmillion** [comment]
Is this what you expect it to look like?
![image](https://user-images.githubusercontent.com/1483210/104832568-ef02af00-585f-11eb-9b43-fa703119b026.png)

**Comment by msbentley** [comment]
Yes, that looks like a MIDAS scan in all its glory - I'll pull the latest and give it a try myself tomorrow! Thanks!

**Comment by msbentley** [comment]
I just gave this a try, but I still seem to hit a problem:
```
In [37]: test = pdr.read('IMG_1627006_1627309_027_ZS.LBL')
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-37-2ec74677de88> in <module>
----> 1 test = pdr.read('IMG_1627006_1627309_027_ZS.LBL')

~/Dropbox/software/pds/pdr/pdr/__init__.py in read(fp)
     11 
     12 def read(fp):
---> 13     return Data(fp)
     14 
     15 def open(fp):

~/Dropbox/software/pds/pdr/pdr/pdr.py in __init__(self, filename)
    632         setattr(self, "pointers", [k for k in self.LABEL.keys() if k[0] == "^"])
    633         try:
--> 634             _ = [
    635                 setattr(
    636                     self,

~/Dropbox/software/pds/pdr/pdr/pdr.py in <listcomp>(.0)
    636                     self,
    637                     pointer[1:] if pointer.startswith("^") else pointer,
--> 638                     pointer_to_function[pointer](filename, self.LABEL),
    639                 )
    640                 for pointer in self.pointers

~/Dropbox/software/pds/pdr/pdr/pdr.py in read_bcr_image(filename, label, pointer)
    605     # TODO: Make this function work.
    606     # This pointer appears in Rosetta / MIDAS data
--> 607     return read_image(filename, label, pointer=pointer)
    608 
    609 pointer_to_function = {

~/Dropbox/software/pds/pdr/pdr/pdr.py in read_image(filename, label, pointer)
    219         prefix = None
    220         if BANDS == 1:
--> 221             image = np.array(struct.unpack(fmt, f.read(pixels * BYTES_PER_PIXEL)))
    222             image = image.reshape(nrows, (ncols + prefix_cols))
    223             if prefix_cols:

error: unpack requires a buffer of 524288 bytes
```

**Comment by cmillion** [comment]
Oh. Ok. I think it's maybe trying to read the LBL as an IMG instead of looking for the IMG. It should work either way, but what happens if you give it the IMG filename instead of the LBL?

**Comment by msbentley** [comment]
Aha, doing that states that no image data can be found, but it does actually read the content OK:
```
In [5]: test = pdr.read('IMG_1627006_1627309_027_ZS.IMG')
No image data identified.

In [6]: test
Out[6]: <pdr.pdr.Data at 0x7f6acf97d0a0>

In [7]: test.BCR_IMAGE
Out[7]: 
array([[15219, 15187, 17623, ..., 17795, 17795, 17799],
       [15222, 15186, 17642, ..., 17798, 17802, 17806],
       [15217, 15189, 17653, ..., 17801, 17801, 17805],
       ...,
       [18378, 19274, 17202, ..., 17406, 17406, 17406],
       [18429, 19277, 17201, ..., 17405, 17405, 17409],
       [18480, 19280, 17196, ..., 17404, 17408, 17412]])
```

**Comment by cmillion** [comment]
Ok. Good. I'll fix the part where it doesn't work if you give it the label and suppress that warning. (The warning is because most PDS images are stored in an object called "IMAGE." So I have special handling for that object name. I'll try to make it more general.)

**Comment by cmillion** [comment]
I think this will work now
    
    lbl = "https://pdssbn.astro.umd.edu/holdings/ro-c-midas-3-ext3-samples-v3.0/data/img/img_1627006_1627309_027_zs.lbl"
    url = "https://pdssbn.astro.umd.edu/holdings/ro-c-midas-3-ext3-samples-v3.0/data/img/img_1627006_1627309_027_zs.img"
    fn = pdr.utils.download_data_and_label(url,lbl=lbl) # downloads the data locally and returns a tuple with local data file and label paths
    assert(pdr.read(fn[0]).BCR_IMAGE.mean()==pdr.read(fn[1]).BCR_IMAGE.mean())

and

    lbl = "https://pds-smallbodies.astro.umd.edu/holdings/ro-c-osinac-4-ext3-67p-m35-reflect-v1.0/data/fit/n20160930t103106740id4bf32.lbl"
    url = "https://pds-smallbodies.astro.umd.edu/holdings/ro-c-osinac-4-ext3-67p-m35-reflect-v1.0/data/fit/n20160930t103106740id4bf32.fit"
    fn = pdr.utils.download_data_and_label(url,lbl=lbl)#None)
    #data = pdr.read(fn[0]) # Reading from image
    #data = pdr.read(fn[1]) # Reading from image
    assert(pdr.read(fn[0]).IMAGE.mean()==pdr.read(fn[1]).IMAGE.mean())

**Comment by msbentley** [comment]
Looks good, thanks!
