### ISSUE TITLE
support the datasets of Galileo in PDS3

### ISSUE THREAD

**Issue by AlimyBreak** [MillionConcepts/pdr#42]
Limited by the network condition that Google is not available in China, I feel sorry for submiting my request here.
Many datasets of  Galileo spacecraft (https://pds-ppi.igpp.ucla.edu/search/?t=Jupiter&sc=Galileo&facet=SPACECRAFT_NAME&depth=1) are not supported by PDR.
Hope you will consider supporting these datasets.

Best regards.

**Comment by m-stclair** [comment]
Completely fine to discuss dataset support in a github issue, no worries.

I suspect that many Galileo data products we don't yet officially support will nevertheless open successfully, so I recommend just trying PDR on the data products you're interested in -- there's a good chance it'll work.

Also, the rest of the Galileo data sets are currently near the top of our support pipeline, so if it _doesn't_ work, it'll probably work soon!

**Comment by AlimyBreak** [comment]
> Completely fine to discuss dataset support in a github issue, no worries.
> 
> I suspect that many Galileo data products we don't yet officially support will nevertheless open successfully, so I recommend just trying PDR on the data products you're interested in -- there's a good chance it'll work.
> 
> Also, the rest of the Galileo data sets are currently near the top of our support pipeline, so if it _doesn't_ work, it'll probably work soon!

Thank you for your excellent works.
Look forward to your support for further datasets.
