### ISSUE TITLE
support for VAX_REAL data type

### ISSUE THREAD

**Issue by Sierra-MC** [MillionConcepts/pdr#46]
Product types currently commented out in ix selection rules that contain this data type:
gal_nims cube
gal_ssi shutter, slope
mgn_altimetry arcdr
pre_magellan pi_venus_img, airsar
pvo imidr (also has VAX_INTEGER and that might be okay, needs review)

**Comment by m-stclair** [comment]
VAX integers should be fine as just LSB integers -- only the VAX floats are weird

**Comment by m-stclair** [comment]
> Might this code be useful for VAX floats? https://github.com/SETI/pds-tools/blob/master/vax.py

Yes, I think so. I stumbled across it a few months ago and it seemed to work well for the couple of test cases I tried. I don't think it's distributed on any package managers, is it? Not that vendoring it would be a huge deal; no one's going to change the VAX float format anytime soon...

**Comment by thareUSGS** [comment]
I don't think it is available via a package manager, but perhaps you can just borrow "vax.py" for PDR with credit? Apache 2.0 license.

There are C and FORTRAN from an old 2010 USGS publication too (public domain of course) : https://pubs.usgs.gov/of/2005/1424/

**Comment by m-stclair** [comment]
e0c3ae7 implements support for 32-bit VAX floats by vendoring vax.py from pds-tools. 

This does not add support for double- or quad-precision VAX floats:
* There are two distinct types of 64-bit VAX float ('D' and 'G'), and there appears to be no mechanism for identifying them in PDS3 metadata, so we do not believe we can provide generalized support for VAX double-precision. We may address this on a case-by-case basis in the future if we are able to perform science-level validation on specific product types that use this data type.
* Support for VAX quad-precision floats pends actually finding some in the archive. 

Closing this issue for now.
