### ISSUE TITLE
Incorrect parsing of bit mask values

### ISSUE THREAD

**Issue by fkmjr** [MillionConcepts/pdr#51]
pdr incorrectly parses a bit mask value as an integer, removing the bit mask after the # character.
Consequently, such a value cannot be retrieved.

Example:
```
OBJECT                            = IMAGE
  SAMPLE_TYPE                     = MSB_INTEGER
  SAMPLE_BITS                     = 16
  SAMPLE_BIT_MASK                 = 2#0000111111111111#
END_OBJECT                        = IMAGE
```
SAMPLE_BIT_MASK is parsed to an integer with the numerical value of 2, removing the bit mask after the # character.
Instead, the result should be a string holding the value of the PDS attribute, e.g. `2#0000111111111111#` in the above example.

**Comment by Sierra-MC** [comment]
Hi, thank you for opening an issue. Can you please provide an example file that this issue is occurring with?

**Comment by fkmjr** [comment]
Example file:
[ZL0_0168_0681869032_144IOF_N0060170ZCAM08180_048085A03.zip](https://github.com/MillionConcepts/pdr/files/12918063/ZL0_0168_0681869032_144IOF_N0060170ZCAM08180_048085A03.zip)
