### ISSUE TITLE
check pandas dtype warning in Voyager LECP S-RDR STEP files

### ISSUE THREAD

**Issue by m-stclair** [MillionConcepts/pdr#59]
`pd.read_csv()` throws a `DtypeWarning` when reading these tables. Check if there is something unusual about their structure causing this and if it can be cleanly addressed; otherwise, consider constructing a special case that suppresses the warning or explicitly passes `low_memory=False`.

**Comment by Sierra-MC** [comment]
Can no longer reproduce the warning.
