### ISSUE TITLE
Change to use actual rms-vax package

### ISSUE THREAD

**Issue by rfrenchseti** [MillionConcepts/pdr#65]
Currently `pdr` includes an old copy of the RMS Node's `vax.py` package from the repo `SETI/pds-tools` (a repo which is now deprecated and mostly empty). This code is out of date. An improved and fully documented version is now available in the `rms-vax` package available at https://pypi.org/project/rms-vax/

I suggest that `pdr` be changed to use the current and maintained code rather than having its own copy. If there are features that you need that we don't currently support, please submit an issue on our repo and we will try to help.

**Comment by Sierra-MC** [comment]
@rfrenchseti thank you for notifying us to this, I appreciate you reaching out and letting us know that there is a supported version. I'll take a look tomorrow and incorporate it appropriately in the coming days.

**Comment by Sierra-MC** [comment]
Changed to use conda rms-vax package in 5652e38b9af4db46c0df6f5f23b083eb935462f5

**Comment by Sierra-MC** [comment]
The new release of pdr (1.3.0) uses rms-vax as a dependency.
