### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by AndrewAnnex** [MillionConcepts/pdr#66]
As part of openjournals/joss-reviews#7256, as PDR is part of planetarypy I believe the project uses those governance documents but at a glance I don't see a code of conduct markdown file in this repository/mentioned in the Readme.

**Comment by Sierra-MC** [comment]
Code of conduct added in [this commit](https://github.com/MillionConcepts/pdr/commit/b02b0a038f167d50e1b29073896305439f1ec483). I used an updated version of the code used by planetarypy
