### ISSUE TITLE
'Data' object has no attribute 'filename' on MEX/VMC image

### ISSUE THREAD

**Issue by msbentley** [MillionConcepts/pdr#7]
I think this worked before the major changes mentioned in #6 but when I try to open the attached Mars Express VMC image I get the following:
```
In [20]: test = read('VMC_SE_200630_105343_039.LBL')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-f92fba6d02bc> in <module>
----> 1 test = read('VMC_SE_200630_105343_039.LBL')

~/Dropbox/software/pds/pdr/pdr/__init__.py in read(fp)
     10 
     11 def read(fp):
---> 12     return Data(fp)
     13 
     14 def open(fp):

~/Dropbox/software/pds/pdr/pdr/pdr.py in __init__(self, fn)
    381             index += [p.strip('^') for p in self.pointers]
    382             try:
--> 383                 _ = [
    384                     setattr(
    385                         self,

~/Dropbox/software/pds/pdr/pdr/pdr.py in <listcomp>(.0)
    385                         self,
    386                         pointer[1:] if pointer.startswith("^") else pointer,
--> 387                         pointer_to_function(pointer)(self, pointer=pointer.strip("^")),
    388                     )
    389                     for pointer in self.pointers

~/Dropbox/software/pds/pdr/pdr/pdr.py in read_image(self, pointer, userasterio)
    108         if not userasterio:
    109             raise
--> 110         dataset = rasterio.open(self.filename)
    111         if len(dataset.indexes)==1:
    112             return dataset.read()[0,:,:] # Make 2D images actually 2D

AttributeError: 'Data' object has no attribute 'filename'
```
[VMC_SE_200630_105343_039.zip](https://github.com/MillionConcepts/pdr/files/5892535/VMC_SE_200630_105343_039.zip)

**Comment by cmillion** [comment]
Ok. This wasn't in my test data yet. That's a weird error because the file should always have a name! Can you give me a URL for that file?

**Comment by msbentley** [comment]
Oh, sorry, I thought that was one I'd mentioned before! Sure, the data are at:

ftp://psa.esac.esa.int/pub/mirror/MARS-EXPRESS/VMC/MEX-M-VMC-2-EDR-EXT7-V1.0/DATA/2020/202006/20200630_1020_1054/VMC_SE_200630_105343_039.LBL

ftp://psa.esac.esa.int/pub/mirror/MARS-EXPRESS/VMC/MEX-M-VMC-2-EDR-EXT7-V1.0/DATA/2020/202006/20200630_1020_1054/VMC_SE_200630_105343_039.RAW

**Comment by cmillion** [comment]
Cool. Thank you. I'm going to use the ones hosted at the PDS because my test framework works with https:
`url = "https://pds-geosciences.wustl.edu/mex/mex-m-vmc-2-edr-ext7-v1/mexvmc_l2_0007/data/2020/202006/20200630_1020_1054/vmc_se_200630_105343_039.raw"`
`lbl = "https://pds-geosciences.wustl.edu/mex/mex-m-vmc-2-edr-ext7-v1/mexvmc_l2_0007/data/2020/202006/20200630_1020_1054/vmc_se_200630_105343_039.lbl"`

**Comment by msbentley** [comment]
Great - to be honest, I hadn't realised that MEX data were also mirrored to PDS!

**Comment by cmillion** [comment]
It seems that it's not, actually, since the link to all of the `.raw` files redirect to an error page. I'm emailing GEO about it.

**Comment by cmillion** [comment]
Fixed, I think.

![image](https://user-images.githubusercontent.com/1483210/106334036-dd55da00-6257-11eb-9ce6-f8a3e50900f9.png)

**Comment by msbentley** [comment]
Confirmed, looks good - many thanks!
