### ISSUE TITLE
delay expensive imports

### ISSUE THREAD

**Issue by m-stclair** [MillionConcepts/pdr#79]
We had done a pretty deep pass at some point on delaying expensive imports (primarily numpy and pandas), but they seem to have crept back in such that `import pdr` also imports numpy and pandas. We should re-delay them and add a test to ensure they remain delayed.

**Comment by Sierra-MC** [comment]
bdb58dd28400d2e09377a50bbcd0da7827710b67 made the necessary changes. 91242204b3649e16cf2f55609fbabdf94da2f560 includes a test to prevent this from reoccurring.
