### ISSUE TITLE
import pdr doesn't work

### ISSUE THREAD

**Issue by alemran042** [MillionConcepts/pdr#9]
I have installed the pdr and "pip list" shows pdr is installed. However, when import pdr, its shows the following error:

import pdr
-------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emran/anaconda3/lib/python3.7/site-packages/pdr/__init__.py", line 3, in <module>
    from pdr.pdr import Data
  File "/home/emran/anaconda3/lib/python3.7/site-packages/pdr/pdr.py", line 264
    if Path(fmtpath:= self.filename.replace(
                   ^
SyntaxError: invalid syntax

**Comment by cmillion** [comment]
The walrus operator didn't exist in Python 3.7. Try it with Python 3.8+. I suggest using a conda environment to do this.

**Comment by cmillion** [comment]
@alemran042 Just curious if this ended up working for you.

**Comment by alemran042** [comment]
Unfortunately, it didn't end up working. I can import pdr but had another issue in reading the image. Here the code and error it shows. Also, copied the **link of data** (https://pds-smallbodies.astro.umd.edu/holdings/nh-p_psa-leisa_mvic-5-comp-v1.0/data/color/)

############## code ########
In [1]: import pdr

In [2]: data = pdr.read_image('mvic_0299178092_0x536_sci_pl.img')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-1112cacd92ac> in <module>
----> 1 data = pdr.read_image('mvic_0299178092_0x536_sci_pl.img')

~/SPAC/Pluto/New Horizons/copied file/Pluto Encounter Surface Composition/data/color/pdr.py in read_image(self, pointer, userasterio)
    134     the use of rasterio until I can figure out how to produce consistent
    135     output."""
--> 136     if (self.filename.lower().endswith('.fits') or
    137             self.filename.lower().endswith('.fit')):
    138         try:  # Is it a FITS file?

AttributeError: 'str' object has no attribute 'filename'

**Comment by alemran042** [comment]
**Update**
I was able to read the image using a different approach. Here is how it ended up working:

In [1]: import pdr
In [2]: img = pdr.rasterio.open('mvic_0299178092_0x536_sci_pl.lbl')
In [3]: data = img.read()
In [4]: data.shape
Out[4]: (4, 4754, 4754)

Thank you,
Emran

**Comment by cmillion** [comment]
Thanks. What made you decide to use `pdr.read_image` instead of `pdr.read`?

What happens if you try `data = pdr.read('mvic_0299178092_0x536_sci_pl.img')`?

Thanks.

**Comment by alemran042** [comment]
@cmillion  I think pdr has no module as read( ), at least in the version I am using. If I try data = pdr.read('mvic_0299178092_0x536_sci_pl.img'), it shows following error:

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9160ed7ad022> in <module>
----> 1 data = pdr.read('mvic_0299178092_0x536_sci_pl.lbl')

AttributeError: module 'pdr' has no attribute 'read'

**Comment by cmillion** [comment]
Ok. That shouldn't happen. Weird. Thank you.

**Comment by cmillion** [comment]
Oh. When `import pdr` are you importing `pdr.py` from, like, within the git directory named `pdr`? Or are you importing the library `pdr` (like from within the directory that contains the directory named `pdr`)?

Or did you pip install `pdr` with something like `pip install git+https://github.com/MillionConcepts/pdr.git`?

**Comment by alemran042** [comment]
@cmillion yes, I install pdr with pip install git+https://github.com/MillionConcepts/pdr.git
Then,  I import the library as "import pdr"

**Comment by alemran042** [comment]
@cmillion ah, I got it. Unconsciously, I had the pdr.py file in the working directory. After deleting the pdr.py file, now pdr.read( ) works. Apology for the confusion. Now, it works as it is supposed to be.
Thank you,
Emran

**Comment by cmillion** [comment]
Great! Glad it's working right. Please let me know if you encounter other issues. Thank you.
